### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by WanLang0** [PSYZ1234/NIDALoc#2]
Hi,PSYZ.Your code is excellent!
I have some questions about output that I would like to ask. The absolute pose of your network output is [t,q], Is **t** the coordinate on the map?Does **gcp** refer to the grid on the map corresponding to each point cloud after dividing the map into grids

**Comment by PSYZ1234** [comment]
Hi, sorry for the late reply. 
(1) Yes, the output 't' is the absolute position of the scene LiDAR point cloud on the map. All positions are in the same world coordinate system. 
(2) Yes, after dividing the grid, we will count which grid the point cloud falls on for each frame.

**Comment by WanLang0** [comment]
OK. Can you provide the Oxford radar dataset ? I encountered many difficulties when downloading the dataset. My email is on my personal page, or how can I contact you. Your answer is very important to me, thank you very much.

**Comment by PSYZ1234** [comment]
Hi, the dataset can only be downloaded from the Oxford official website because it is too large to be shared through online sending. If you want to copy it directly offline, you can come to me. I am at NTU, Singapore.

**Comment by WanLang0** [comment]
I have obtained this dataset, thank you for your help.
